export const strings = {
  auth: {
    title: 'Sign in',
    subtitle: 'Sign in with an account that has visitor permissions.',
    emailLabel: 'Email',
    emailPlaceholder: 'name@company.com',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter your password',
    signInCta: 'Sign in',
    showPasswordA11y: 'Show password',
    hidePasswordA11y: 'Hide password',
    emailRequired: 'Email is required.',
    passwordRequired: 'Password is required.',
    invalidEmail: 'Please enter a valid email address.',
    invalidPassword: 'Password must be at least 6 characters.',
    loginFailed: 'Login failed.',
    noVisitorAccess: 'Your account does not have visitor access.',
  },
  home: {
    title: 'Visitor Management',
    welcome: (name: string) => `Welcome, ${name}`,
    subtitle: 'Tap CHECK-IN to register a visitor.',
    gallerySubtitle: 'Swipe to view photos for your location.',
    checkIn: 'CHECK-IN',
    addVisitor: 'Add visitor',
    viewVisitors: 'View visitors',
    signOut: 'Sign out',
    noActions: 'You do not have visitor permissions on this account.',
    loadingImages: 'Loading gallery...',
    loadImagesFailed: 'Could not load gallery images.',
    noImages: 'No gallery images available',
    closePanel: 'Close',
  },
  checkIn: {
    title: 'Visitor Check-In',
    back: 'Back',
    next: 'Next',
    complete: 'Complete check-in',
    submitFailed: 'Could not complete check-in.',
    contactRequired: 'Enter a phone number or email.',
    purposeRequired: 'Select a purpose of visit.',
    hostRequired: 'Enter the host name.',
    photoRequired: 'Capture a visitor photo to continue.',
    steps: {
      contact: 'Contact',
      personal: 'Personal',
      host: 'Host',
      photo: 'Photo',
      summary: 'Summary',
    },
    contactTitle: 'How can we reach you?',
    contactSubtitle: 'Enter mobile number and email for notifications.',
    personalTitle: 'Tell us your name',
    personalSubtitle: 'This will appear on your visitor badge.',
    hostTitle: 'Who are you visiting?',
    hostSubtitle: 'Select purpose and host details.',
    photoTitle: 'Capture your photo',
    photoSubtitle: 'A clear photo helps security identify you quickly.',
    summaryTitle: 'Review and confirm',
    summarySubtitle: 'Check your details before completing check-in.',
    success: 'Visitor checked in successfully.',
  },
  addVisitor: {
    phoneLabel: 'Phone',
    phonePlaceholder: 'Phone number',
    emailLabel: 'Email',
    emailPlaceholder: 'visitor@email.com',
    nameLabel: 'Full name',
    namePlaceholder: 'Visitor name',
    purposeLabel: 'Purpose',
    hostNameLabel: 'Host name',
    hostNamePlaceholder: 'Person to meet',
    hostEmailLabel: 'Host email',
    hostEmailPlaceholder: 'host@company.com',
    organizationLabel: 'Organization',
    organizationPlaceholder: 'Visitor company',
    departmentLabel: 'Department',
    departmentPlaceholder: 'Department',
    nameRequired: 'Visitor name is required.',
    invalidHostEmail: 'Please enter a valid host email.',
  },
  visitors: {
    title: 'Visitors',
    subtitle: 'Recent visitor records for your location.',
    searchPlaceholder: 'Search by name, email, or host',
    empty: 'No visitors found.',
    loadFailed: 'Could not load visitors.',
    checkIn: 'Check in',
    checkOut: 'Check out',
    back: 'Back',
    status: {
      pending: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      checked_in: 'Checked in',
      checked_out: 'Checked out',
    },
  },
} as const;

